web/router.ex
defmodule Enquete.Router do
  use Enquete.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Enquete do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/enquetes", EnqueteController do
      resources "/answers", AnswerController
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", Enquete do
  #   pipe_through :api
  # end


end

lib/enquete/endpoint.ex
defmodule Enquete.Endpoint do
  use Phoenix.Endpoint, otp_app: :enquete

  socket "/socket", Enquete.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :enquete, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_enquete_key",
    signing_salt: "mCYsFSov"

  plug Enquete.Router
end

lib/enquete/repo.ex
defmodule Enquete.Repo do
  use Ecto.Repo, otp_app: :enquete
end

web/models/enquete.ex
defmodule Enquete.Enquete do
  use Enquete.Web, :model

  schema "enquetes" do
    field :title, :string

    timestamps
  end

  @required_fields ~w(title)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/enquete_controller.ex
defmodule Enquete.EnqueteController do
  use Enquete.Web, :controller

  alias Enquete.Enquete

  plug :scrub_params, "enquete" when action in [:create, :update]

  def index(conn, _params) do
    enquetes = Repo.all(Enquete)
    render(conn, "index.html", enquetes: enquetes)
  end

  def new(conn, _params) do
    changeset = Enquete.changeset(%Enquete{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"enquete" => enquete_params}) do
    changeset = Enquete.changeset(%Enquete{}, enquete_params)

    case Repo.insert(changeset) do
      {:ok, _enquete} ->
        conn
        |> put_flash(:info, "Enquete created successfully.")
        |> redirect(to: enquete_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    enquete = Repo.get!(Enquete, id)
    render(conn, "show.html", enquete: enquete)
  end

  def edit(conn, %{"id" => id}) do
    enquete = Repo.get!(Enquete, id)
    changeset = Enquete.changeset(enquete)
    render(conn, "edit.html", enquete: enquete, changeset: changeset)
  end

  def update(conn, %{"id" => id, "enquete" => enquete_params}) do
    enquete = Repo.get!(Enquete, id)
    changeset = Enquete.changeset(enquete, enquete_params)

    case Repo.update(changeset) do
      {:ok, enquete} ->
        conn
        |> put_flash(:info, "Enquete updated successfully.")
        |> redirect(to: enquete_path(conn, :show, enquete))
      {:error, changeset} ->
        render(conn, "edit.html", enquete: enquete, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    enquete = Repo.get!(Enquete, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(enquete)

    conn
    |> put_flash(:info, "Enquete deleted successfully.")
    |> redirect(to: enquete_path(conn, :index))
  end
end

web/views/enquete_view.ex
defmodule Enquete.EnqueteView do
  use Enquete.Web, :view
end

web/templates/enquete/edit.html.eex
<h2>Edit enquete</h2>

<%= render "form.html", changeset: @changeset,
                        action: enquete_path(@conn, :update, @enquete) %>

<%= link "Back", to: enquete_path(@conn, :index) %>

web/templates/enquete/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/enquete/index.html.eex
<h2>アンケートリスト</h2>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for enquete <- @enquetes do %>
    <tr>
      <td><%= enquete.title %></td>

      <td class="text-right">
        <%= link "Show Answers", to: enquete_answer_path(@conn, :index, enquete), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: enquete_path(@conn, :edit, enquete), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: enquete_path(@conn, :delete, enquete), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New enquete", to: enquete_path(@conn, :new) %>

web/templates/enquete/new.html.eex
<h2>New enquete</h2>

<%= render "form.html", changeset: @changeset,
                        action: enquete_path(@conn, :create) %>

<%= link "Back", to: enquete_path(@conn, :index) %>

web/templates/enquete/show.html.eex
<h2>Show enquete</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @enquete.title %>
  </li>

</ul>

<%= link "Edit", to: enquete_path(@conn, :edit, @enquete) %>
<%= link "Back", to: enquete_path(@conn, :index) %>