web/router.ex
defmodule Enquete.Router do
  use Enquete.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Enquete do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/enquetes", EnqueteController do
      resources "/answers", AnswerController
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", Enquete do
  #   pipe_through :api
  # end


end

web/models/answer.ex
defmodule Enquete.Answer do
  use Enquete.Web, :model

  schema "answers" do
    field :answerer, :string
    belongs_to :enquete, Enquete.Enquete
    has_many :details, Enquete.AnswerDetail, on_delete: :delete_all

    timestamps
  end

  @required_fields ~w(answerer enquete_id)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/answer_controller.ex
defmodule Enquete.AnswerController do
  use Enquete.Web, :controller
  require Logger

  alias Enquete.Answer
  alias Enquete.AnswerDetail

  plug :scrub_params, "answer" when action in [:create, :update]

  def index(conn, %{"enquete_id" => enquete_id}) do
    details_query = from ad in AnswerDetail, order_by: ad.no
    answers = Repo.all(
      from a in Answer,
        where: a.enquete_id == ^enquete_id,
      select: a,
      preload: [details: ^details_query]
    )
    render(conn, "index.html", answers: answers, enquete_id: enquete_id)
  end

  def new(conn, %{"enquete_id" => enquete_id}) do
    changeset = Answer.changeset(%Answer{})
    render(conn, "new.html", changeset: changeset, enquete_id: enquete_id)
  end

  def create(conn, %{"answer" => answer_params}) do
    changeset = Answer.changeset(%Answer{}, %{
        enquete_id: answer_params["enquete_id"],
        answerer: answer_params["answerer"]
      })

    case Repo.transaction(fn ->
      _answer = Repo.insert!(changeset)

      # TODO なんかいい感じに...
      Repo.insert!(AnswerDetail.changeset(%AnswerDetail{}, %{
          answer_id: _answer.id,
          no: 1,
          answer_string: answer_params["answer_string0"]
        }))

      Repo.insert!(AnswerDetail.changeset(%AnswerDetail{}, %{
          answer_id: _answer.id,
          no: 2,
          answer_string: answer_params["answer_string1"]
        }))

      Repo.insert!(AnswerDetail.changeset(%AnswerDetail{}, %{
          answer_id: _answer.id,
          no: 3,
          answer_string: answer_params["answer_string2"]
        }))

      Repo.insert!(AnswerDetail.changeset(%AnswerDetail{}, %{
          answer_id: _answer.id,
          no: 4,
          answer_string: answer_params["answer_string3"]
        }))

      Repo.insert!(AnswerDetail.changeset(%AnswerDetail{}, %{
          answer_id: _answer.id,
          no: 5,
          answer_string: answer_params["answer_string4"]
        }))

      _answer
    end) do
      {:ok, _answer} ->
        conn
        |> put_flash(:info, "Answer created successfully.")
        |> redirect(to: enquete_answer_path(conn, :index, answer_params["enquete_id"]))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, enquete_id: changeset["enquete_id"])
    end
  end

  def show(conn, %{"id" => id}) do
    answer = Repo.get!(Answer, id)
    render(conn, "show.html", answer: answer)
  end

  def edit(conn, %{"id" => id}) do
    answer = Repo.get!(Answer, id) |> Repo.preload(:details)
    changeset = Answer.changeset(answer)

    render(conn, "edit.html", answer: answer, changeset: changeset, enquete_id: answer.enquete_id)
  end

  def update(conn, %{"id" => id, "answer" => answer_params}) do
    details_query = from ad in AnswerDetail, order_by: ad.no
    answer = Repo.get!(Answer, id) |> Repo.preload([details: details_query])

    changeset = Answer.changeset(answer, %{
        enquete_id: answer_params["enquete_id"],
        answerer: answer_params["answerer"]
      })

    case Repo.transaction(fn ->
      _answer = Repo.update!(changeset)

      # TODO なんかいい感じに...
      Repo.update!(AnswerDetail.changeset(Enum.at(answer.details, 0), %{
          answer_string: answer_params["answer_string0"]
        }))

      Repo.update!(AnswerDetail.changeset(Enum.at(answer.details, 1), %{
          answer_string: answer_params["answer_string1"]
        }))

      Repo.update!(AnswerDetail.changeset(Enum.at(answer.details, 2), %{
          answer_string: answer_params["answer_string2"]
        }))

      Repo.update!(AnswerDetail.changeset(Enum.at(answer.details, 3), %{
          answer_string: answer_params["answer_string3"]
        }))

      Repo.update!(AnswerDetail.changeset(Enum.at(answer.details, 4), %{
          answer_string: answer_params["answer_string4"]
        }))

      _answer
    end) do
      {:ok, _answer} ->
        conn
        |> put_flash(:info, "Answer updated successfully.")
        |> redirect(to: enquete_answer_path(conn, :show, answer.enquete_id, answer))
      {:error, changeset} ->
        render(conn, "edit.html", answer: answer, changeset: changeset, enquete_id: answer.enquete_id)
    end
  end

  def delete(conn, %{"id" => id}) do
    answer = Repo.get!(Answer, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(answer)

    conn
    |> put_flash(:info, "Answer deleted successfully.")
    |> redirect(to: enquete_answer_path(conn, :index, answer.enquete_id))
  end
end

web/views/answer_view.ex
defmodule Enquete.AnswerView do
  use Enquete.Web, :view

  require Logger

  def answer_string(answer, index) do
    # TODO パターンマッチとかにできるよね？？
    if Ecto.assoc_loaded?(answer.details) do
      if length(answer.details) >= (index + 1) do
        str = Enum.at(answer.details, index).answer_string
        if str do
          str
        else
          ""
        end
      else
        ""
      end
    else
      ""
    end
  end
end

web/templates/answer/edit.html.eex
<h2>回答を編集する</h2>

<%= render "form.html", enquete_id: @answer.enquete_id, changeset: @changeset,
                        action: enquete_answer_path(@conn, :update, @enquete_id, @answer) %>

<%= link "Back", to: enquete_answer_path(@conn, :index, @answer.enquete_id) %>

web/templates/answer/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= hidden_input f, :enquete_id, value: @enquete_id %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :answerer, class: "control-label" do %>
      回答者
    <%= end %>
    <%= text_input f, :answerer, class: "form-control" %>
    <%= error_tag f, :answerer %>
  </div>

  <div class="form-group">
    <%= label f, :answer_string0, class: "control-label" do %>
      テキストを読むだけでなく、例えや経験談を交えて、分かりやすく説明していたか？
    <%= end %>
    <%= select f, :answer_string0, 5..1, class: "form-control", value: answer_string(@changeset.model, 0) %>
    <%= error_tag f, :answer_string0 %>
  </div>

  <div class="form-group">
    <%= label f, :answer_string1, class: "control-label" do %>
      話や説明だけでなく、研修生に質問したり意見を求めたりして、一方的な講義にならないようにしていたか？
    <%= end %>
    <%= select f, :answer_string1, 5..1, class: "form-control", value: answer_string(@changeset.model, 1) %>
    <%= error_tag f, :answer_string1 %>
  </div>

  <div class="form-group">
    <%= label f, :answer_string2, class: "control-label" do %>
      大切なことを話す時は、「重要ですよ。」と声をかけたり板書したりして、ノートを取ることを促していたか？
    <%= end %>
    <%= select f, :answer_string2, 5..1, class: "form-control", value: answer_string(@changeset.model, 2) %>
    <%= error_tag f, :answer_string2 %>
  </div>

  <div class="form-group">
    <%= label f, :answer_string3, class: "control-label" do %>
      良かったところ
    <%= end %>
    <%= textarea f, :answer_string3, class: "form-control", value: answer_string(@changeset.model, 3) %>
    <%= error_tag f, :answer_string3 %>
  </div>

  <div class="form-group">
    <%= label f, :answer_string4, class: "control-label" do %>
      悪かったところ
    <%= end %>
    <%= textarea f, :answer_string4, class: "form-control", value: answer_string(@changeset.model, 4) %>
    <%= error_tag f, :answer_string4 %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/answer/index.html.eex
<h2>アンケート回答リスト</h2>
<ol>
  <li>テキストを読むだけでなく、例えや経験談を交えて、分かりやすく説明していたか？</li>
  <li>話や説明だけでなく、研修生に質問したり意見を求めたりして、一方的な講義にならないようにしていたか？</li>
  <li>大切なことを話す時は、「重要ですよ。」と声をかけたり板書したりして、ノートを取ることを促していたか？</li>
  <li>よかったところ</li>
  <li>わるかったところ</li>
</ol>
<table class="table">
  <thead>
    <tr>
      <th>回答者</th>
      <th>1.</th>
      <th>2.</th>
      <th>3.</th>
      <th>4.</th>
      <th>5.</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for answer <- @answers do %>
    <tr>
      <td><%= answer.answerer %></td>
  <%= for detail <- answer.details do %>
      <td><%= detail.answer_string %></td>
  <% end %>
      <td class="text-right">
        <%= link "Edit", to: enquete_answer_path(@conn, :edit, @enquete_id, answer), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: enquete_answer_path(@conn, :delete, @enquete_id, answer), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New answer", to: enquete_answer_path(@conn, :new, @enquete_id) %><br>
<%= link "Back to enquetes", to: enquete_path(@conn, :index) %>

web/templates/answer/new.html.eex
<h2>回答する</h2>

<%= render "form.html", enquete_id: @enquete_id, changeset: @changeset,
                        action: enquete_answer_path(@conn, :create, @enquete_id) %>

<%= link "Back", to: enquete_answer_path(@conn, :index, @enquete_id) %>

web/templates/answer/show.html.eex
<h2>回答</h2>

<ul>

  <li>
    <strong>Answerer:</strong>
    <%= @answer.answerer %>
  </li>

  <li>
    <strong>Enquete:</strong>
    <%= @answer.enquete_id %>
  </li>

</ul>

<%= link "Edit", to: enquete_answer_path(@conn, :edit, @answer.enquete_id, @answer) %>
<%= link "Back", to: enquete_answer_path(@conn, :index, @answer.enquete_id) %>